on:
  push:
    types:
    - opened
    - synchronize
    - edited
    
jobs:
  job1:
    uses: 404Hack/NewDevTeam/.github/workflows/WelcomeTeam.yml@main
  job2:
    uses: 404Hack/NewDevTeam/.github/workflows/Send_Result.yml@main
  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      # Deploy to Test Environment current job
      - name: Checkout
        uses: actions/checkout@v3
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            COMPLETE
