name: Send_Result

on:
  workflow_run:
    workflows: ["WelcometoTeam"]
    types:
      - completed

jobs:
  Welcome:
    uses: 404Hack/NewDevTeam/.github/workflows/WelcomeTeam.yml@main
    
  send-flag-to-chat:
    runs-on: ubuntu-latest
    needs: [Welcome]
    steps:
      - name: Enviar mensaje a Slack
        if: ${{ github.event.pull_request.user.login != github.repository_owner }}
        env:
          FLAG: ${{ secrets.FLAG }}
          URL: ""
        run: |
          SECRETO="$FLAG"
          curl -X POST -H 'Content-type: application/json' --data '{
            "message": "Todas las condiciones se han cumplido con éxito. Secreto: $SECRETO"
          }' $URL
