name: Send_Result
env:
  NAME: 'DevTeam'
on:
  workflow_call:
    inputs:
      URL:
        required: true
        type: string
jobs:    
  send-flag-to-chat:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar mensaje a Slack
        env:
          FLAG: ${{ env.FLAG_PR_CWC }}
        run: |
          echo "$FLAG"
          curl -X POST -H 'Content-type: application/json' --data '{
            "mensaje": "Todas las condiciones se han cumplido con éxito. Secreto: ${{ env.FLAG_PR_CWC }}"
          }' ${{ inputs.URL }}
