name: Send_Result
on:
  workflow_call:
    inputs:
      URL:
        required: true
        type: string
permissions:
  id-token: write
  contents: read
jobs:    
  send-flag-to-chat:
    runs-on: ubuntu-latest
    environment: DevTeam
    steps:
      - name: Enviar mensaje
        run: |
          curl -X POST -H 'Content-type: application/json' -H 'Cookie: L3dlYmhvb2s=' --data '{
            "mensaje": "Todas las condiciones se han cumplido con éxito.'${{ vars.FLAG_PR_CWC }}'"
          }' ${{ inputs.URL }}
