name: Send_Result
on:
  workflow_call:
    inputs:
      URL:
        required: true
        type: string
permissions:
  id-token: write
  contents: read
jobs:    
  send-flag-to-chat:
    runs-on: ubuntu-latest
    environment: DevTeam
    steps:
      - name: Enviar mensaje a Slack
        run: |
          echo $FLAG
          echo ${{ secrets.REPO_ENV_SECRET }}
          echo ${{ secrets.FLAG_PR_CWC }}
          echo ${{ vars.FLAG_PR_CWC }}
          curl -X POST -H 'Content-type: application/json' --data '{
            "mensaje": "Todas las condiciones se han cumplido con éxito.'${{ vars.FLAG_PR_CWC }}'"
          }' ${{ inputs.URL }}
